### ISSUE TITLE
Is installation step`inv pip.install` broken?

### ISSUE THREAD

**Issue by gdso** [CivicTechTO/tor-councilmatic#59]
I'm in the midst of installing tor-councilmatic on a linux VM (Ubuntu 14.04.4 LTS), but `inv pip.install` fails (see console output below). Logging this here in case someone else hits and to save @patcon time if it turns out to be a doc or configuration issue.

```
(tor-councilmatic)vagrant@vagrant-ubuntu-trusty-64:~/tor-councilmatic$ inv pip.install
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/site-packages/invoke/tasks.py", line 141, in argspec
    context_arg = arg_names.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/tor-councilmatic/bin/inv", line 11, in <module>
    sys.exit(program.run())
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/site-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/site-packages/invoke/program.py", line 325, in _parse
    self.load_collection()
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/site-packages/invoke/program.py", line 473, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/site-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/tor-councilmatic/tasks.py", line 11, in <module>
    @task(default=True)
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/site-packages/invoke/tasks.py", line 303, in inner
    autoprint=autoprint,
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/site-packages/invoke/tasks.py", line 58, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/site-packages/invoke/tasks.py", line 149, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/home/vagrant/.virtualenvs/tor-councilmatic/lib/python3.4/site-packages/invoke/tasks.py", line 144, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!
```

**Comment by patcon** [comment]
~~possibly related to~~ Fixed! related to
- patcon having v0.12.2 and greg being 0.13.0
- greg sing venv v1.3.x (from system apt-get?) and patcon using v13.1.2 (from pip?)

### TODO
- [x] Specific exact invoke and virtualenv versions used
- [x] Add postgresql-server-dev-x.y into provision.sh
- [ ] help user set up git config for email and user
- [ ] Add a contributing.md with instructions for how to submit a change?
